-- =============================================================================
-- AML (Anti-Money Laundering) Tables
-- Banking Data Platform
-- =============================================================================
-- These tables support AML/Financial Crime detection and monitoring.
-- Referenced by ~3% of banking JDs (GoTymeX, UOB, MB Bank).
-- =============================================================================

-- ── AML Rules ───────────────────────────────────────────────────────────────
-- Rules engine configuration for detecting suspicious patterns
CREATE TABLE IF NOT EXISTS core_banking.aml_rule (
    rule_id         BIGINT PRIMARY KEY,
    rule_name       VARCHAR(200) NOT NULL,
    rule_code       VARCHAR(50) NOT NULL UNIQUE,
    rule_type       VARCHAR(50) NOT NULL,
        -- VELOCITY: High frequency transactions in short window
        -- AMOUNT: Transaction amount exceeds threshold
        -- GEOGRAPHIC: Unusual location patterns
        -- STRUCTURING: Multiple transactions just below reporting threshold
        -- PATTERN: Complex pattern detection
        -- PEPS: Politically Exposed Persons screening
    description     TEXT,
    threshold       NUMERIC(18,2),
    threshold_currency VARCHAR(3) DEFAULT 'VND',
    window_hours    INT,
    severity        VARCHAR(20) NOT NULL DEFAULT 'MEDIUM',
        -- LOW: Monitoring only
        -- MEDIUM: Alert generated
        -- HIGH: Auto-block + alert
        -- CRITICAL: Escalate to compliance
    is_active       SMALLINT DEFAULT 1,
    regulatory_ref  VARCHAR(100),  -- Reference to regulation (e.g., 'TT 35/2019/TT-NHNN')
    created_by      VARCHAR(100) DEFAULT 'SYSTEM',
    created_at      TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMP NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE core_banking.aml_rule IS 'AML detection rules engine configuration';
COMMENT ON COLUMN core_banking.aml_rule.rule_type IS 'Rule category: VELOCITY, AMOUNT, GEOGRAPHIC, STRUCTURING, PATTERN, PEPS';
COMMENT ON COLUMN core_banking.aml_rule.severity IS 'Alert severity: LOW, MEDIUM, HIGH, CRITICAL';

-- ── AML Alerts ─────────────────────────────────────────────────────────────
-- Generated alerts from rule triggers and suspicious activity detection
CREATE TABLE IF NOT EXISTS core_banking.aml_alert (
    alert_id            BIGINT PRIMARY KEY,
    alert_number        VARCHAR(30) NOT NULL UNIQUE,  -- Auto-generated: AML-YYYYMMDD-NNNNN
    rule_id             BIGINT REFERENCES core_banking.aml_rule(rule_id),
    transaction_id      BIGINT,  -- FK to txn_account (nullable for pattern-based alerts)
    card_txn_id         BIGINT,  -- FK to card_crm.card_txn (nullable)
    customer_id         BIGINT NOT NULL,  -- FK to customer
    account_id          BIGINT,  -- FK to account (nullable)

    -- Alert details
    alert_type          VARCHAR(50) NOT NULL,
        -- LARGE_CASH_TRANSACTION
        -- VELOCITY_BREACH
        -- STRUCTURING_DETECTED
        -- GEOGRAPHIC_ANOMALY
        -- UNUSUAL_PATTERN
        -- PEPS_MATCH
        -- SANCTIONS_MATCH
        -- CTR_REQUIRED  (Currency Transaction Report)
        -- SAR_REQUIRED  (Suspicious Activity Report)

    risk_score          NUMERIC(5,2) NOT NULL,  -- 0.00 - 100.00
    risk_category       VARCHAR(20) NOT NULL,
        -- LOW: Score 0-30
        -- MEDIUM: Score 31-60
        -- HIGH: Score 61-80
        -- CRITICAL: Score 81-100

    description         TEXT NOT NULL,
    evidence_json       JSONB,  -- Supporting evidence: transaction details, patterns

    -- Transaction context
    txn_amount          NUMERIC(18,2),
    txn_date            TIMESTAMP,
    channel             VARCHAR(20),

    -- Investigation
    status              VARCHAR(20) NOT NULL DEFAULT 'OPEN',
        -- OPEN: New alert, pending review
        -- IN_REVIEW: Under investigation
        -- ESCALATED: Sent to compliance officer
        -- STR_FALSE_POSITIVE: Confirmed false positive
        -- STR_FILED: Suspicious Transaction Report filed
        -- CLOSED: Investigation complete

    analyst_id          BIGINT,  -- FK to employee (compliance analyst)
    priority            VARCHAR(10) DEFAULT 'MEDIUM',
    due_date            DATE,
    notes               TEXT,

    -- Regulatory
    ctr_required        SMALLINT DEFAULT 0,  -- Currency Transaction Report required
    sar_filed           SMALLINT DEFAULT 0,  -- Suspicious Activity Report filed
    sar_reference       VARCHAR(50),

    -- Timestamps
    created_at          TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMP NOT NULL DEFAULT NOW(),
    resolved_at         TIMESTAMP
);

COMMENT ON TABLE core_banking.aml_alert IS 'AML alerts generated by detection rules';
COMMENT ON COLUMN core_banking.aml_alert.risk_score IS 'Risk score 0-100, higher = more suspicious';
COMMENT ON COLUMN core_banking.aml_alert.status IS 'Alert workflow status: OPEN→IN_REVIEW→ESCALATED→STR_FILED/CLOSED';

-- ── AML Alert Transactions (linking table) ─────────────────────────────────
-- Links alerts to multiple transactions (one alert can cover multiple txns)
CREATE TABLE IF NOT EXISTS core_banking.aml_alert_transaction (
    alert_id        BIGINT NOT NULL REFERENCES core_banking.aml_alert(alert_id),
    transaction_id  BIGINT NOT NULL,  -- FK to txn_account
    created_at      TIMESTAMP NOT NULL DEFAULT NOW(),
    PRIMARY KEY (alert_id, transaction_id)
);

-- ── AML Customer Risk Profile ──────────────────────────────────────────────
-- Customer risk scoring for AML purposes
CREATE TABLE IF NOT EXISTS core_banking.aml_customer_risk (
    customer_id         BIGINT PRIMARY KEY,  -- FK to customer
    risk_level          VARCHAR(20) NOT NULL DEFAULT 'STANDARD',
        -- STANDARD: Normal customer
        -- ELEVATED: Requires enhanced monitoring
        -- HIGH: Frequent alerts, requires senior review
        -- PROHIBITED: Blocked from certain transactions

    risk_score          NUMERIC(5,2) NOT NULL DEFAULT 0,
    peps_flag           SMALLINT DEFAULT 0,  -- Politically Exposed Person
    sanctions_flag      SMALLINT DEFAULT 0,  -- On sanctions list
    adverse_media_flag  SMALLINT DEFAULT 0,  -- Adverse media hits

    total_alerts        INT DEFAULT 0,
    open_alerts         INT DEFAULT 0,
    last_alert_date     DATE,
    last_review_date    DATE,
    next_review_date    DATE,

    -- Enhanced Due Diligence
    edd_required        SMALLINT DEFAULT 0,
    edd_reason          TEXT,
    source_of_wealth    VARCHAR(100),
    expected_activity   TEXT,

    created_at          TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMP NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE core_banking.aml_customer_risk IS 'Customer AML risk profiles for screening';

-- ── Indexes ────────────────────────────────────────────────────────────────
CREATE INDEX IF NOT EXISTS idx_aml_alert_status ON core_banking.aml_alert(status);
CREATE INDEX IF NOT EXISTS idx_aml_alert_customer ON core_banking.aml_alert(customer_id);
CREATE INDEX IF NOT EXISTS idx_aml_alert_created ON core_banking.aml_alert(created_at);
CREATE INDEX IF NOT EXISTS idx_aml_alert_risk ON core_banking.aml_alert(risk_category);
CREATE INDEX IF NOT EXISTS idx_aml_rule_type ON core_banking.aml_rule(rule_type);
